<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons[
<!ELEMENT person (name, gender, email, birthyear, hero, spandex, strength, speed, inteliggence, wealth, income, tax)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT birthyear (#PCDATA)>
<!ELEMENT hero (#PCDATA)>
<!ELEMENT spandex (#PCDATA)>
<!ELEMENT strength (#PCDATA)>
<!ELEMENT speed (#PCDATA)>
<!ELEMENT intelligence (#PCDATA)>
<!ELEMENT wealth (#PCDATA)>
<!ELEMENT income (#PCDATA)>
<!ELEMENT tax (#PCDATA)>
]>
<persons>
  <person>
    <name>Nick Nedd</name>
    <gender>Male</gender>
    <email>nick@tick.com</email>
    <birthyear>1976</birthyear>
    <hero>The Tick</hero>
    <spandex>Yes</spandex>
    <strength>9</strength>
    <speed>7</speed>
    <intelligence>5</intelligence>
    <wealth>0</wealth>
    <income>90287</income>
    <tax>29794</tax>
  </person>
  <person>
    <name>Bruce Wayne</name>
    <gender>Male</gender>
    <email>bruce@wayneenterprises.com</email>
    <birthyear>1974</birthyear>
    <hero>Batman</hero>
    <spandex>No</spandex>
    <strength>7</strength>
    <speed>4</speed>
    <intelligence>9</intelligence>
    <wealth>50144501</wealth>
    <income>3343891</income>
    <tax>11132384</tax>
  </person>
  <person>
    <name>Selina Kyle</name>
    <gender>Femle</gender>
    <email>selina@whiskas.com</email>
    <birthyear>1977</birthyear>
    <hero>Catwoman</hero>
    <spandex>Yes</spandex>
    <strength>6</strength>
    <speed>6</speed>
    <intelligence>9</intelligence>
    <wealth>2987323</wealth>
    <income>0</income>
    <tax>598464</tax>
  </person>
</persons>
